name: Deploy Django to Railway

on:
  push:
    branches:
      - main  # деплой з гілки main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Python 3.13 ще може глючити на Railway

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Deploy to Railway
        uses: railwayapp/railway-deploy@v2
        with:
          service: GAME_SITE_main
          environment: production   # 🟢 додай це
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
