name: CI/CD (Django → Heroku)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Git LFS pull
        run: |
          git lfs install
          git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install OS deps (mysqlclient)
        run: |
          sudo apt-get update
          sudo apt-get install -y libmysqlclient-dev

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django system checks
        env:
          DJANGO_SETTINGS_MODULE: config.settings
        run: |
          python manage.py check

  deploy:
    name: Deploy to Heroku
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && secrets.HEROKU_API_KEY && secrets.HEROKU_APP_NAME && secrets.HEROKU_EMAIL }}
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Git LFS pull
        run: |
          git lfs install
          git lfs pull

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
          dontuseforce: true
          rollbackonhealthcheckfailed: true
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/"
          checkstring: ""
          delay: 10

